abstract type Variable end

"""
    canonical_name(var::Variable) -> Symbol

Return the canonical name of a variable as a symbol.
The canonical name is the primary identifier for a variable,
and all aliases for that variable will map to this canonical name.

# Example
```julia-repl
julia> canonical_name(CloudCover())
:cc
```
"""
function canonical_name(::Type{T}) where {T <: Variable}
    throw(MethodError(canonical_name, (T,)))  # enforce per-type method
end

"""
    from_name(x::Union{Symbol, String, Val}) -> Variable
    from_name(x::Variable) -> Variable

Convert a canonical variable name to its corresponding `Variable` type instance. Do nothing
if the input i already is a `Variable`.

# Example
```julia-repl
julia> from_name(:cc)
CloudCover()

julia> from_name(from_name(:cc))
CloudCover()
```
"""
from_name(x::Symbol) = from_name(Val(x))
from_name(x::String) = from_name(Symbol(x))
from_name(x::Variable) = x

"""
    canonical_NAME(var::Variable) -> String

Return the canonical name of a variable as an uppercase string.
This is useful for matching variable names in datasets that use uppercase naming conventions.

# Example
```julia-repl
julia> canonical_NAME(CloudCover())
"CC"
```
"""
canonical_NAME(var) = uppercase(string(canonical_name(var)))


"""
    longname(var::Variable) -> String

Return a human-readable long name for the variable, suitable for display in plots and tables.
By default, this is generated by converting the variable type name from CamelCase to a
underscore-separated lowercase string. For example, `CloudCover` would become `cloud_cover`.

You can override this by providing a custom long name when defining the variable type.

# Example
```julia-repl
julia> longname(CloudCover())
:cloud_cover
```
"""
longname(::T) where {T <: Variable} = Symbol(camelcase_to_words(string(nameof(T)), '_'))

"""
    pretty_name(var::Variable) -> String

Return a pretty name for the variable, which can be used in contexts where a more concise or stylized name is desired.
By default, this is generated by converting the variable type name from CamelCase to a space-separated lowercase string.
For example, `CloudCover` would become `cloud cover`.

You can override this by providing a custom pretty name when defining the variable type.

# Example
```julia-repl
julia> pretty_name(CloudCover())
"cloud cover"
```
"""
pretty_name(::T) where {T <: Variable} = camelcase_to_words(string(nameof(T)), ' ')

"""
    all_variables() -> Vector{Variable}

Return a vector of instances of all defined `Variable` subtypes.
"""
all_variables() = [T() for T in subtypes(Variable)]
all_canonical_names() = canonical_name.(all_variables())

function summary_variables(subset::Vector{Variable} = all_variables())
    x1 = map(var -> (var, longname(var), canonical_NAME(var), sha(var)), subset)
    x2 = TypedTables.Table(;
        variable = getindex.(x1, 1),
        longname = getindex.(x1, 2),
        canonical_NAME = getindex.(x1, 3),
        sha = getindex.(x1, 4),
    )
    return x2
end

"""
    @defvariable TypeName canonical_name

Define a `Variable` subtype and automatically
register `canonical_name` and `from_name` methods for it.
"""
macro defvariable(T, canonical, sha = nothing)
    return quote
        struct $(esc(T)) <: Variable end
        $(esc(:canonical_name))(::$(esc(T))) = $(QuoteNode(canonical))
        $(esc(:from_name))(::Val{$(QuoteNode(canonical))}) = $(esc(T))()
        $(esc(:sha))(::$(esc(T))) = $(sha)
    end
end

@defvariable CloudCover cc "3e24f0d040fb10a44e47c0d0065edbf48688c27948b8ac1f30b2de6e6db182bb"
@defvariable WindDirection dd "0fe438168776fb7beb384cb3ba1257ae5c74770e917ca9c949440a04189dfad2"
@defvariable WindSpeed fg "a38e9e812e6b00f54aeda8a5ae65faf9cbfad84c1f59f4bc010fad87f05c20c8"
@defvariable WindGust fx "287c6440c0e4f6bc55185b676c77e235039372fc0324e1460aadaaa927b7ae6f"
@defvariable Humidity hu "aeb5115c2050b830f356ffe86a3a354e4c0d3a12f362b69f022e188f2b82ed7e"
@defvariable SeaLevelPressure pp "5450696a0df010a9e9e2b0d063d4054caab3bec28b68439fe55c73c5214686c4"
@defvariable GlobalRadiation qq "92a2e64377ff7c2cb841307b28435a14fb577cc560d912e6527b5b1a675e4e0c"
@defvariable PrecipitationAmount rr "4c18349e24b952ffc09a96fa439edeb7ab204b13c955b36f90cffb342f687daa"
@defvariable SnowDepth sd "5100f26849dfbf01f38c612b987aad39b3b49acf5127b2f2c1d8ed604522b493"
@defvariable SunshineDuration ss "2e8ab89edd1f1fba798df27e429e393c6bb14b868b483334fc31a193671ebdd0"
@defvariable MeanTemperature tg "e7440855706947ea185a30ed4b57ea0f37031d484b8a8be43e87143ac0efe19f"
@defvariable MinimumTemperature tn "447e11a903490b63e9b159530a12dd60a80b8f9e55c8dec6ce861c310e2e2d4c"
@defvariable MaximumTemperature tx "8249f3ed31b2a94b3649dd8660f5b7f21cd235dd1733e3b3edd0855d9726cae9"
